## playstore Data analysis project

In [ ]:
from logging import exception
import mysql.connector as mc
import seaborn as sns
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [6]:
df.shape

(2312944, 24)

In [9]:
pd.set_option('display.max_columns', 30)

In [10]:
df = pd.read_csv('Google-Playstore.csv')
df.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,Currency,Size,Minimum Android,Developer Id,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,USD,10M,7.1 and up,Jean Confident Irénée NIYIZIBYOSE,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,USD,2.9M,5.0 and up,Webserveis,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,USD,3.7M,4.0.3 and up,Cabin Crew,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,USD,1.8M,4.0.3 and up,Climate Smart Tech2,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,USD,6.2M,4.1 and up,Rafal Milek-Horodyski,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35

In [17]:
### filtering the columns

new_df = df[['App Name','Category','Rating','Rating Count','Installs','Minimum Installs',
    'Maximum Installs','Free','Price','Currency','Size','Released','Last Updated',
   'Ad Supported','In App Purchases']]

In [18]:
new_df.head()

,App Name,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,Currency,Size,Released,Last Updated,Ad Supported,In App Purchases
0,Gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,USD,10M,"Feb 26, 2020","Feb 26, 2020",False,False
1,Ampere Battery Info,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,USD,2.9M,"May 21, 2020","May 06, 2021",True,False
2,Vibook,Productivity,0.0,0.0,50+,50.0,58,True,0.0,USD,3.7M,"Aug 9, 2019","Aug 19, 2019",False,False
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,5.0,5.0,10+,10.0,19,True,0.0,USD,1.8M,"Sep 10, 2018","Oct 13, 2018",True,False
4,GROW.me,Tools,0.0,0.0,100+,100.0,478,True,0.0,USD,6.2M,"Feb 21, 2020","Nov 12, 2018",False,False

In [21]:
new_df.isnull().sum()

App Name                2
Category                0
Rating              22883
Rating Count        22883
Installs              107
Minimum Installs      107
Maximum Installs        0
Free                    0
Price                   0
Currency              135
Size                  196
Released            71053
Last Updated            0
Ad Supported            0
In App Purchases        0
dtype: int64

In [23]:
categorical_data = new_df.select_dtypes('O')
categorical_data.head()

,App Name,Category,Installs,Currency,Size,Released,Last Updated
0,Gakondo,Adventure,10+,USD,10M,"Feb 26, 2020","Feb 26, 2020"
1,Ampere Battery Info,Tools,"5,000+",USD,2.9M,"May 21, 2020","May 06, 2021"
2,Vibook,Productivity,50+,USD,3.7M,"Aug 9, 2019","Aug 19, 2019"
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,10+,USD,1.8M,"Sep 10, 2018","Oct 13, 2018"
4,GROW.me,Tools,100+,USD,6.2M,"Feb 21, 2020","Nov 12, 2018"

In [30]:
numerical_data = new_df.select_dtypes(exclude=['O','bool'])
numerical_data.head()

   Rating  Rating Count  Minimum Installs  Maximum Installs  Price
0     0.0           0.0              10.0                15    0.0
1     4.4          64.0            5000.0              7662    0.0
2     0.0           0.0              50.0                58    0.0
3     5.0           5.0              10.0                19    0.0
4     0.0           0.0             100.0               478    0.0

In [27]:
boolian_data = new_df.select_dtypes(include='bool')
boolian_data.head()

   Free  Ad Supported  In App Purchases
0  True         False             False
1  True          True             False
2  True         False             False
3  True          True             False
4  True         False             False

In [ ]:
### to load this dataset in mysql

df = sns.load_dataset('iris') 
df = df.drop_duplicates()
df['sepal_width'] = df['sepal_width'].astype(int)
print(df.duplicated().sum())
conn=mc.connect(host ='localhost' , user = 'root' , password = 'Jigar@975919', database='ineuron')
if(conn.is_connected()):
    print('jai ho mata Rani')
else:
    print('unable to connect')

myc  = conn.cursor()
query= "insert into iris (idd , sepal_len , sepal_width , petal_len,petal_width,species) values(%s,%s,%s,%s,%s,%s)"
values = []
for i in range(df.shape[0]):
    values.append((i,df['sepal_length'][i],df['sepal_width'][i],df['petal_length'][i],df['petal_width'][i],df['species'][i]))

print(data[0])
# myc.executemany(query,data)
# conn.commit()
# print(myc.rowcount, "row inserted")
try:
    myc.executemany(query,data)
    conn.commit()
    print(myc.rowcount, "row inserted")
except :
    # print(e)
    print('unable to insert data')
    conn.rollback()
myc.close()
conn.close()